### ISSUE TITLE
Recommended write capacity for podyn_migration_ tables

### ISSUE THREAD

**Issue by peterjuras** [citusdata/podyn#4]
Hi!

We're evaluating Podyn for a DDB -> PostgreSQL replication and love what we are seeing so far!

What is the recommended Write Capacity for the podyn_migration_ tables? It appears that podyn tries to work at the capacity limit, i.e. if I increase the capacity it tries to fully use it, which triggers the default DynamoDB alarms because they are expecting a utilization of ~75%.

What is the recommended setting? (Optimally based on the Write Capacity of the table that is replicated)

**Comment by marcocitus** [comment]
The DynamoDB docs do some hand waving on this (e.g. see "capacity for DynamoDB leases table"):
https://aws.amazon.com/blogs/big-data/processing-amazon-dynamodb-streams-using-the-amazon-kinesis-client-library/

The number of shards corresponds to the number of entries in the the podyn_migration tables. Podyn will write a checkpoint for each shard at most twice per second. Reads should be less frequent (once per 20 seconds per shard).

**Comment by peterjuras** [comment]
Thanks for the answer and the link!
